# Generated by Django 3.2.20 on 2023-09-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_invoice',
            name='cadrs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recurring_invoice',
            name='cemail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
