# Generated by Django 3.2.20 on 2023-09-04 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0003_auto_20230904_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankcreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('branch', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('ac_no', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('ifsc', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('opn_bal', models.FloatField(blank=True, null=True)),
                ('bal_type', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='bank/')),
                ('status', models.TextField(default='active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromB', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('toB', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('adjtype', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('adjacname', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.bankcreation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
