# Generated by Django 3.2.20 on 2023-09-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0004_bankcreation_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcreation',
            name='status',
            field=models.TextField(default='Active'),
        ),
    ]
