# Generated by Django 4.2.1 on 2023-09-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0010_recurring_bills_items_hsn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurring_bills_items',
            name='hsn',
        ),
        migrations.AddField(
            model_name='recurring_bills',
            name='hsn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
