# Generated by Django 4.2.1 on 2023-09-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0012_remove_recurring_bills_bills_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurring_bills',
            old_name='hsn',
            new_name='bill_no',
        ),
    ]
