# Generated by Django 4.2.1 on 2023-09-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0014_recurring_bills_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_bills',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
