# Generated by Django 4.2.1 on 2023-09-26 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0016_recurring_bills_amt_paid_rec_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='rec_comments',
            name='recur_bills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.recurring_bills'),
        ),
    ]
