# Generated by Django 4.2.1 on 2023-09-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0018_remove_rec_comments_customr'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_bills',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurring_bills',
            name='amt_paid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
